"""ACC persistence contract.

One facade (`Store`) for every collection. Two implementations:
  - InMemoryStore  : local, tests, offline demo
  - FirestoreStore : Cloud Run + Firestore (durable source of truth, Doc 09 §7)

Mission state is the source of truth: compute is allowed to disappear.
"""
from __future__ import annotations

from typing import Any, Protocol

from domain.models import (
    AgentExecution,
    AgentRecord,
    Approval,
    AuditEvent,
    Checkpoint,
    MemoryEntry,
    Mission,
    MissionEvent,
    PolicyDecision,
    RecoveryAttempt,
    SecurityEvent,
    Task,
)


class Store(Protocol):
    # --- Missions ----------------------------------------------------------
    async def save_mission(self, mission: Mission) -> Mission: ...
    async def get_mission(self, mission_id: str) -> Mission | None: ...
    async def list_missions(self, status: str | None = None, limit: int = 50) -> list[Mission]: ...
    async def update_mission(self, mission: Mission, expected_version: int) -> Mission: ...

    # --- Taches ------------------------------------------------------------
    async def save_task(self, task: Task) -> Task: ...
    async def get_task(self, mission_id: str, task_id: str) -> Task | None: ...
    async def list_tasks(self, mission_id: str) -> list[Task]: ...
    async def claim_task(
        self, mission_id: str, task_id: str, expected: set[str], owner: str
    ) -> Task | None: ...

    # --- Evenements --------------------------------------------------------
    async def append_event(self, event: MissionEvent) -> MissionEvent: ...
    async def list_events(self, mission_id: str, limit: int = 500) -> list[MissionEvent]: ...
    async def last_event_id(self, mission_id: str) -> str | None: ...

    # --- Executions --------------------------------------------------------
    async def save_execution(self, execution: AgentExecution) -> AgentExecution: ...
    async def list_executions(self, mission_id: str) -> list[AgentExecution]: ...

    # --- Checkpoints -------------------------------------------------------
    async def save_checkpoint(self, checkpoint: Checkpoint) -> Checkpoint: ...
    async def get_checkpoint(self, mission_id: str, checkpoint_id: str) -> Checkpoint | None: ...
    async def list_checkpoints(self, mission_id: str) -> list[Checkpoint]: ...

    # --- Recovery ----------------------------------------------------------
    async def save_recovery(self, recovery: RecoveryAttempt) -> RecoveryAttempt: ...
    async def get_recovery(self, mission_id: str, recovery_id: str) -> RecoveryAttempt | None: ...
    async def list_recoveries(self, mission_id: str) -> list[RecoveryAttempt]: ...

    # --- Gouvernance -------------------------------------------------------
    async def save_policy_decision(self, decision: PolicyDecision) -> PolicyDecision: ...
    async def list_policy_decisions(self, mission_id: str) -> list[PolicyDecision]: ...
    async def save_approval(self, approval: Approval) -> Approval: ...
    async def get_approval(self, approval_id: str) -> Approval | None: ...
    async def list_approvals(
        self, mission_id: str | None = None, status: str | None = None
    ) -> list[Approval]: ...

    # --- Memoire / audit ---------------------------------------------------
    async def save_memory(self, entry: MemoryEntry) -> MemoryEntry: ...
    async def list_memory(self, mission_id: str) -> list[MemoryEntry]: ...
    async def save_audit(self, event: AuditEvent) -> AuditEvent: ...
    async def list_audit(self, mission_id: str) -> list[AuditEvent]: ...
    async def save_security_event(self, event: SecurityEvent) -> SecurityEvent: ...
    async def list_security_events(self, mission_id: str | None = None) -> list[SecurityEvent]: ...

    # --- Registre d'agents -------------------------------------------------
    async def save_agent(self, agent: AgentRecord) -> AgentRecord: ...
    async def get_agent(self, agent_id: str) -> AgentRecord | None: ...
    async def list_agents(self) -> list[AgentRecord]: ...

    # --- Idempotence (Doc 08 §27) -----------------------------------------
    async def get_idempotent(self, key: str) -> dict[str, Any] | None: ...
    async def put_idempotent(self, key: str, value: dict[str, Any]) -> None: ...

    async def reset(self) -> None: ...
